#.predefined variables & Use defined variables
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml




trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CmdLine@2
      displayName: 'Run a one-line script'
      inputs:
        script: echo Hello, world!
    - task: CmdLine@2
      displayName: 'Run a multi-line script'
      inputs:
        script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml

          -bash:


          echo "repo name : $(Build.Repository.Name)"
    - task: CmdLine@2
      inputs:
        script: |
          var1=$(var1)
          var2=$(var2)
          str1=$(str1)
          str2=$(str2)

          sum=$(($var1 + $var2))
          sub=$(($var1 - $var2))
          mul=$(($var1 * $var2))
          div=$(($var2 / $var1))
          concat="${var1} ${var2}"
          concatstrings="${str1} ${str2}"

          echo "variable1 : $var1"
          echo "variable2 : $var2"
          echo "String1 : $str1"
          echo "String2 : $str2"


          echo "Sum Of variables : $sum"
          echo "Subtraction Of variables : $sub"
          echo "Multiplication Of variables : $mul"
          echo "Division Of variables : $div"
          echo "concatenate Of variables : $concat"
          echo "concatenate Of strings : $concatstrings"


          echo "Array:[ $sum $sub $mul.$div.$concat"]

          echo "Matrix:
          [ $sum $sub ]
          [ $mul $div"]

          Array=([0]=$sum [1]=$sub [2]=$mul [3]=$concat)
          Array[4]='$concatstrings'
          echo "${Array[@]}"
          echo "${!Array[@]}"
          echo "${#Array[@]}"
          echo "${Array[0]}"

          



          echo "repo name : $(Build.Repository.Name)"
          echo "Agent.Id : $(Agent.Id)"
          echo "Agent.JobName : $(Agent.JobName)"
          echo "Agent.JobStatus : $(Agent.JobStatus)"
          echo "Agent.MachineName : $(Agent.MachineName)"
          echo "Agent.Name : $(Agent.Name)"
          echo "Agent.OS : $(Agent.OS)"
          echo "Agent.OSArchitecture : $(Agent.OSArchitecture)"
          echo "Agent.TempDirectory : $(Agent.TempDirectory)"
          echo "Agent.ToolsDirectory : $(Agent.ToolsDirectory)"
          echo "Agent.WorkFolder : $(Agent.WorkFolder)"

