trigger:
  branches:
     include:
      - main
variables:
  - group: sum_variable_group

stages:
- stage: __default
  jobs:
  - job: Job1A
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CmdLine@2
      displayName: 'Run a one-line script'
      inputs:
        script: echo Hello, world!

  - job: Job1B

  - job: Job1C
  - job: Job1D
