trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: sum_variable_group



stages:
- stage: STAGE_1
  displayName: 'STAGE_1'
  jobs:
  
  - job: Job1A
    steps:
    - task: CmdLine@2
      displayName: 'Run a one-line script'
      inputs:
        script: echo Hello, world!

  - job: Job1B
  - job: Job1C
  - job: Job1D
  - job: Job1E
